#####################################################
## Purpose: Makefile for Chap_5_Basic_OOP/exercise5
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:03:47  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/09 13:26:38  Greg
## Initial check-in
##
#####################################################
FILES =  top.sv classPackage.sv testBench.sv Calc2_DesignFiles/calc2_top.sv oop.sv
TOPLEVEL = top

include Makefile_non_DPI

